name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  get_it: ^8.0.3
  cloud_firestore: ^5.6.5
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_contacts: ^1.1.9+2
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The flutter_launcher_icons package is used to generate launcher icons.
  flutter_launcher_icons: ^0.14.3

  # The flutter_lints package contains a set of recommended lints to
  # encourage good coding practices. 
  flutter_lints: ^5.0.0

# Correct location for flutter_launcher_icons configuration (outside flutter section)
flutter_launcher_icons:
  android: "launcher_icon"  # Specifies the name of the launcher icon for Android.
  ios: true  # Ensures the icon is also generated for iOS.
  image_path: "assets/images/Chatter.png"  # Path to your app's launcher icon image.

flutter:
  # This enables the use of Material Design icons in your app.
  uses-material-design: true

  # If you want to add assets (e.g., images, fonts) to your app, you would add
  # them in the following section:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add custom fonts here if needed.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
