// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTbFBeB5ak-kEnSSxL9hhFUC5TaM9EEQ',
    appId: '1:650031909517:web:54f39a7af5ddb1a9cfb0c4',
    messagingSenderId: '650031909517',
    projectId: 'chatapp-a7b10',
    authDomain: 'chatapp-a7b10.firebaseapp.com',
    storageBucket: 'chatapp-a7b10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6d8ZhWfL4wpuX5q3MnW_U8LeZ4mCHzJA',
    appId: '1:650031909517:android:de0c56996f3c7cf8cfb0c4',
    messagingSenderId: '650031909517',
    projectId: 'chatapp-a7b10',
    storageBucket: 'chatapp-a7b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCB-ThQN1ZG0Al0gdG1uAMGEPszfzsoY0',
    appId: '1:650031909517:ios:2acb7a2cab071c44cfb0c4',
    messagingSenderId: '650031909517',
    projectId: 'chatapp-a7b10',
    storageBucket: 'chatapp-a7b10.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCB-ThQN1ZG0Al0gdG1uAMGEPszfzsoY0',
    appId: '1:650031909517:ios:2acb7a2cab071c44cfb0c4',
    messagingSenderId: '650031909517',
    projectId: 'chatapp-a7b10',
    storageBucket: 'chatapp-a7b10.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrTbFBeB5ak-kEnSSxL9hhFUC5TaM9EEQ',
    appId: '1:650031909517:web:fc18af02ec6c69f1cfb0c4',
    messagingSenderId: '650031909517',
    projectId: 'chatapp-a7b10',
    authDomain: 'chatapp-a7b10.firebaseapp.com',
    storageBucket: 'chatapp-a7b10.firebasestorage.app',
  );
}
